// src/lib/catalog.js — single source of truth for the showcase home page.
// Edit ROI figures here as practice benchmarks firm up; all are indicative.

export const CATALOG = [
  {
    id: 'story-forge',
    name: 'Story Forge',
    phase: 'Plan',
    tagline: 'Requirements in, sprint-ready stories out.',
    description:
      'Converts raw business requirements — BRD extracts, workshop notes, emails — into INVEST-compliant user stories with Gherkin acceptance criteria, mapped Guidewire touchpoints, Fibonacci estimates with rationale, explicit dependencies and open questions for the BA.',
    benefits: [
      'Removes the blank-page problem for BAs and product owners',
      'Stories arrive pre-mapped to GW constructs, so estimation starts informed',
      'Negative-path ACs generated by default — fewer gaps found in testing',
      'JSON shape is Jira/Azure DevOps import-ready'
    ],
    roi: [
      { metric: '40–60%', label: 'less effort per story written' },
      { metric: '~2 days', label: 'saved per sprint of backlog grooming' },
      { metric: 'Fewer', label: 'AC gaps reaching SIT/UAT' }
    ],
    taxonomy: {
      'AI pattern': 'Structured generation (single-pass)',
      Products: 'PC · CC · BC · Cross-suite',
      Input: 'Free-text requirements',
      Output: 'Epic + stories JSON (saved to project)',
      Persistence: 'Neon Postgres artifact'
    },
    config: [
      { param: 'Primary product', values: 'PolicyCenter / ClaimCenter / BillingCenter / Cross-suite' },
      { param: 'Requirements text', values: 'Free text, any length up to model context' }
    ]
  },
  {
    id: 'code-review',
    name: 'Code Review Copilot',
    phase: 'Build',
    tagline: 'Principal-level Guidewire review on every commit-sized chunk.',
    description:
      'Reviews Gosu, PCF, integration, GX and batch code against Guidewire Cloud standards. Returns severity-calibrated findings (critical → info) with line-level locations, concrete fixes naming the GW construct to use, upgrade-safety flags and an overall code-health score.',
    benefits: [
      'Defects caught at desk-check cost, not SIT cost',
      'Upgrade-safety category protects Guidewire Cloud update cadence',
      'Consistent standards across India / Spain / Morocco delivery centres',
      'Junior developers get senior-grade feedback on demand'
    ],
    roi: [
      { metric: '30%', label: 'fewer human review cycles' },
      { metric: '10×', label: 'cheaper to fix at review vs UAT (industry heuristic)' },
      { metric: '0', label: 'reviewer calendar time consumed' }
    ],
    taxonomy: {
      'AI pattern': 'Structured analysis with severity calibration',
      Products: 'PC · CC · BC · Cross-suite',
      Input: 'Code (line-numbered automatically)',
      Output: 'Scored findings JSON + quick wins',
      Persistence: 'Neon Postgres artifact'
    },
    config: [
      { param: 'Product', values: 'PC / CC / BC / Cross-suite' },
      { param: 'Code type', values: 'Gosu / PCF / Integration / GX / Batch / Rules' },
      { param: 'Review profiles', values: 'Standards · Performance · Upgrade/Cloud safety · Security (multi-select)' }
    ]
  },
  {
    id: 'test-strategist',
    name: 'Test Strategist',
    phase: 'Test',
    tagline: 'Pyramid-balanced coverage, harness chosen per case.',
    description:
      'Derives executable test cases from a story, code or defect — choosing GUnit, GT-API, GT-UI or manual per case to keep the pyramid healthy. Calls out the test data to stage before execution and harness-specific automation notes.',
    benefits: [
      'Test design keeps pace with development instead of lagging a sprint',
      'Harness selection enforced — no GT-UI tests for logic GUnit should own',
      'Staged test data list kills the #1 cause of blocked test execution',
      'Traceability: each case names the AC it covers'
    ],
    roi: [
      { metric: '50%', label: 'faster test-case design' },
      { metric: 'Higher', label: 'automation ratio via pyramid discipline' },
      { metric: 'Fewer', label: 'blocked tests from missing data' }
    ],
    taxonomy: {
      'AI pattern': 'Structured generation with classification',
      Products: 'PC · CC · BC',
      Input: 'Story + ACs, code, or defect text',
      Output: 'Typed test cases JSON + data + notes',
      Persistence: 'Neon Postgres artifact'
    },
    config: [
      { param: 'Input kind', values: 'Story+ACs / Code / Defect description' },
      { param: 'Material', values: 'Free text or code' }
    ]
  },
  {
    id: 'release-navigator',
    name: 'Release Navigator',
    phase: 'Release',
    tagline: 'Know what the next ski release does to you before it lands.',
    description:
      'Two lenses on release readiness: a 16-practice CI/CD maturity self-check with live scoring, and AI impact analysis of your customisation inventory against the target Guidewire Cloud platform release — per-area impact, remediation actions, regression focus, effort band and a pre-upgrade checklist.',
    benefits: [
      'Upgrade planning starts from evidence, not guesswork',
      'Effort band supports AMS commercial conversations early',
      'Regression focus per area shapes the test pack before code lands',
      'Readiness checklist doubles as a CI/CD maturity assessment for new accounts'
    ],
    roi: [
      { metric: '20–30%', label: 'less upgrade regression effort via targeting' },
      { metric: 'Weeks', label: 'earlier visibility of remediation work' },
      { metric: '2-in-1', label: 'maturity assessment + impact analysis' }
    ],
    taxonomy: {
      'AI pattern': 'Structured analysis + static scoring',
      Products: 'PC · CC · BC (multi-select)',
      Input: 'Customisation inventory + target release',
      Output: 'Risk-rated impact JSON + checklist',
      Persistence: 'Neon Postgres artifact (incl. readiness %)'
    },
    config: [
      { param: 'Target release', values: 'Innsbruck / Hakuba / Garmisch / Las Leñas / Palisades / Next' },
      { param: 'Products in scope', values: 'PC / CC / BC (multi-select)' },
      { param: 'Readiness checklist', values: '16 practices across 4 groups' }
    ]
  },
  {
    id: 'defect-triage',
    name: 'Defect Triage Agent',
    phase: 'Operate',
    agentic: true,
    tagline: 'Four agents work the case — and send it back when confidence is low.',
    description:
      'A multi-agent pipeline that triages production defects autonomously. An Intake Agent structures the raw ticket; an Investigator forms ranked root-cause hypotheses with confidence scores; a Router assigns team, priority and ticket type — or loops the case back with a focused directive when confidence falls below 65% (max 2 loops); a Fix Planner writes the workaround, permanent fix, regression coverage and prevention step. Every handoff renders on a live timeline with inspectable agent output.',
    benefits: [
      'L2/L3 triage happens in minutes, around the clock',
      'Self-correction loop is a demonstrable agentic capability for client showcases',
      'Handoff notes give receiving teams cause + evidence, not just a symptom',
      'Confidence scores make the AI\u2019s certainty explicit and auditable'
    ],
    roi: [
      { metric: '35–50%', label: 'faster mean-time-to-triage' },
      { metric: '24/7', label: 'first-pass triage coverage' },
      { metric: 'Lower', label: 'misrouting and ticket ping-pong' }
    ],
    taxonomy: {
      'AI pattern': 'Multi-agent orchestration with self-correction loop',
      Agents: 'Intake → Investigator → Router (⟲) → Fix Planner',
      Products: 'PC · CC · BC · Cross-suite',
      Input: 'Defect report + optional logs/code',
      Output: 'Full case file JSON (4 agent outputs)',
      Persistence: 'Neon Postgres artifact'
    },
    config: [
      { param: 'Product / Environment', values: 'PC / CC / BC / Cross-suite · Prod / Pre-prod / UAT / SIT / Dev' },
      { param: 'Loop threshold', values: 'Confidence < 65% triggers re-investigation' },
      { param: 'Loop budget', values: 'Max 2 extra passes (MAX_LOOPS in DefectTriage.jsx)' },
      { param: 'Evidence', values: 'Optional logs / stack trace / code — raises confidence' }
    ]
  }
]

export const SHARED_CONFIG = [
  { param: 'ANTHROPIC_API_KEY', values: 'Vercel env var — server-side only, powers all agents' },
  { param: 'ANTHROPIC_MODEL', values: 'Optional override, defaults to claude-sonnet-4-6' },
  { param: 'DATABASE_URL', values: 'Neon pooled connection string (plain env var, not a Secret)' }
]
