#!/usr/bin/env python3
"""Generate Guidewire AI accelerators slide pack using the NTT DATA Global Insurance template."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from pptx import Presentation
from pptx.util import Emu, Pt

ROOT = Path(__file__).resolve().parent.parent
TEMPLATE = ROOT / "docs" / "templates" / "PPT_Global_Insurance_Guidewire_Template_2025.pptx"
DEMO_DIR = ROOT / "docs" / "media"
OUT = ROOT / "docs" / "guidewire-ai-accelerators-slide-pack.pptx"

# Layout shortcuts (slide master index, layout index)
LAYOUT_TITLE_IMAGE = (6, 0)       # With Footer — title slides
LAYOUT_TITLE_ONLY = (3, 0)        # Section dividers
LAYOUT_TITLE_1COL = (3, 1)
LAYOUT_TITLE_SUB_2COL = (3, 6)    # Title, Subtitle, 2 Column Body Text
LAYOUT_TITLE_SUB_1COL = (3, 5)

ACCELERATORS = [
    {
        "id": "story-forge",
        "name": "Story Forge",
        "phase": "Plan",
        "tagline": "Requirements in, sprint-ready Guidewire stories out",
        "purpose": (
            "Eliminates the blank-page problem for BAs and product owners. Converts raw "
            "requirements into INVEST-compliant user stories with Gherkin acceptance criteria, "
            "mapped Guidewire touchpoints, Fibonacci estimates and explicit dependencies."
        ),
        "example": (
            "Input: Workshop notes — 'Underwriter must apply multi-vehicle discount on mid-term change.'\n"
            "Output: ST-1 with Given/When/Then ACs, touchpoints (PolicyLine, RatingPlugin), 5 story points, "
            "open question on discount eligibility rules."
        ),
        "capabilities": [
            "Negative-path ACs generated by default",
            "JSON export ready for Jira / Azure DevOps",
            "Per-project RAG over client standards",
        ],
        "prod": [
            "Pilot on live backlog grooming; map JSON fields to Jira",
            "Add client story templates to Project knowledge (RAG)",
            "Gate with auth + tenant scoping before client data",
        ],
        "roi": "40–60% less effort per story",
    },
    {
        "id": "code-review",
        "name": "Code Review Copilot",
        "phase": "Build",
        "tagline": "Principal-level Guidewire review on every commit-sized chunk",
        "purpose": (
            "Catches defects at desk-check cost — not SIT cost. Reviews Gosu, PCF, integration, "
            "GX and batch code against bundled GW Cloud standards with severity-calibrated findings "
            "and upgrade-safety flags."
        ),
        "example": (
            "Input: 40-line Gosu enhancement with gw.transaction inside a PCF handler.\n"
            "Output: critical finding (UI-layer transaction), major (query in loop), score 62, "
            "quick wins ranked; optional merge with SonarQube report."
        ),
        "capabilities": [
            "Profiles: Standards · Performance · Upgrade · Security",
            "Bundled GW Cloud standards injected per profile",
            "External static-analysis merge (Sonar, ESLint, Checkstyle)",
        ],
        "prod": [
            "Pre-PR gate in CI; store findings as project artifacts",
            "Index client coding standards into Project knowledge",
            "Add schema validation + golden eval set on prompt changes",
        ],
        "roi": "30% fewer human review cycles",
    },
    {
        "id": "test-strategist",
        "name": "Test Strategist",
        "phase": "Test",
        "tagline": "Pyramid-balanced coverage — harness chosen per case",
        "purpose": (
            "Keeps test design pace with development. Derives executable cases from stories, "
            "code or defects; assigns GUnit, GT-API, GT-UI or Manual per case and lists test "
            "data to stage before execution."
        ),
        "example": (
            "Input: FNOL user story with acceptance criteria.\n"
            "Output: TC-1 GT-UI journey, TC-2 GUnit reserve rules, TC-3 GT-API claim create; "
            "test data manifest (in-force policy, vehicle VIN)."
        ),
        "capabilities": [
            "Enforces test pyramid discipline",
            "Traceability: each case names the AC it covers",
            "Automation notes per harness",
        ],
        "prod": [
            "Feed sprint stories automatically from ALM webhook",
            "Export cases to Zephyr/qTest CSV transform",
            "Combine with Flow Automator for GT-UI cases",
        ],
        "roi": "50% faster test-case design",
    },
    {
        "id": "flow-automator",
        "name": "Flow Automator",
        "phase": "Test",
        "tagline": "Common Guidewire flows scripted in Katalon — PC, CC, BC & Jutro",
        "purpose": (
            "Scaffolds keyword-driven Katalon UI automation for everyday regression journeys. "
            "Generated scripts match the bundled /katalon accelerator — real @Keyword signatures "
            "injected from the repo, not invented method names."
        ),
        "example": (
            "Input: PolicyCenter — 'New PA submission → quote → bind'.\n"
            "Output: Runnable Groovy test case calling PolicyCenterActions.createPersonAccount, "
            "startSubmission, quote, issuePolicy; prerequisites and keyword additions listed."
        ),
        "capabilities": [
            "12 ready-to-run flows in /katalon companion project",
            "Defensive OOTB / data-test locators",
            "Product-specific keyword libraries bundled into prompt",
        ],
        "prod": [
            "Open /katalon in Katalon Studio; adapt locators per client env",
            "Run headless via katalonc in CI with profile secrets",
            "Regenerate scripts after screen customisation via Flow Automator",
        ],
        "roi": "60%+ faster first-draft UI automation",
    },
    {
        "id": "test-migrator",
        "name": "Test Migrator",
        "phase": "Test",
        "tagline": "Manual test cases in, automated scripts out — gaps flagged",
        "purpose": (
            "Converts legacy manual regression packs (Excel, Zephyr, qTest) into runnable "
            "automation across five frameworks. Per case: honest verdict, gap analysis and "
            "test-data manifest — not just a script."
        ),
        "example": (
            "Input: TC-PC-014 manual bind scenario pasted from Excel.\n"
            "Output: Katalon Groovy script, verdict automate-with-fixes, gap (missing "
            "underwriter precondition), test data (person account — generate)."
        ),
        "capabilities": [
            "Frameworks: Katalon · GT · Playwright · Selenium · Cucumber",
            "Pipeline: split → convert per case → synthesise suite",
            "Katalon output aligned to /katalon libraries",
        ],
        "prod": [
            "Batch-convert client UAT pack in pilot week 2–4",
            "Fix gaps in manual cases before CI promotion",
            "Wire converted Katalon scripts into regression suite",
        ],
        "roi": "70%+ faster manual-to-automation conversion",
    },
    {
        "id": "release-navigator",
        "name": "Release Navigator",
        "phase": "Release",
        "tagline": "Know what the next ski release does to you before it lands",
        "purpose": (
            "Combines CI/CD maturity self-check (16 practices) with AI impact analysis of "
            "customisation inventory vs target ski release — per-area risk, remediation, "
            "regression focus and effort band."
        ),
        "example": (
            "Input: Palisades target, PC+CC, inventory (IG flows, entity extensions, PCF overrides).\n"
            "Output: medium overall risk, high-impact IG area, pre-upgrade checklist, "
            "20–30% regression effort reduction via targeted test focus."
        ),
        "capabilities": [
            "Bundled ski-release upgrade themes per target release",
            "Live CI/CD readiness scoring in UI",
            "Per-area regression focus for test planning",
        ],
        "prod": [
            "Maintain living customisation inventory in Project knowledge",
            "Re-run per ski release; attach official GW release notes to RAG",
            "Feed regression focus into Test Strategist / Katalon suite",
        ],
        "roi": "20–30% less upgrade regression effort",
    },
    {
        "id": "defect-triage",
        "name": "Defect Triage Agent",
        "phase": "Operate",
        "tagline": "Four agents work the case — loop back when confidence is low",
        "purpose": (
            "Agentic L2/L3 triage in minutes, 24/7. Intake → Investigator → Router (self-corrects "
            "if confidence < 65%, max 2 loops) → Fix Planner. Live timeline shows every handoff."
        ),
        "example": (
            "Input: Production defect — payment posting failure + Datadog log export.\n"
            "Output: P2 routed to Billing, top hypothesis 72% confidence, workaround, "
            "permanent fix in BC payment plugin, regression GT-API cases listed."
        ),
        "capabilities": [
            "Multi-agent pipeline with confidence-gated loop",
            "Datadog live log query + bulk triage (max 5 errors)",
            "Full case file JSON saved to project",
        ],
        "prod": [
            "Connect Datadog (DD_API_KEY) for live evidence",
            "Index client runbooks in Project knowledge",
            "Integrate output with ServiceNow / Jira ticket enrichment",
        ],
        "roi": "35–50% faster mean-time-to-triage",
    },
]


def delete_all_slides(prs: Presentation) -> None:
    while len(prs.slides) > 0:
        slide_id = prs.slides._sldIdLst[0]
        rId = slide_id.rId
        prs.part.drop_rel(rId)
        del prs.slides._sldIdLst[0]


def get_layout(prs: Presentation, master_idx: int, layout_idx: int):
    return prs.slide_masters[master_idx].slide_layouts[layout_idx]


def find_placeholder(slide, idx: int):
    for shape in slide.shapes:
        if shape.is_placeholder and shape.placeholder_format.idx == idx:
            return shape
    return None


def set_ph_text(shape, text: str, font_size: int = 14) -> None:
    if shape is None:
        return
    tf = shape.text_frame
    tf.clear()
    p = tf.paragraphs[0]
    p.text = text
    p.font.size = Pt(font_size)


def set_body_bullets(shape, sections: list[tuple[str, list[str] | str]], font_size: int = 11) -> None:
    if shape is None:
        return
    tf = shape.text_frame
    tf.clear()
    first = True
    for heading, body in sections:
        if not first:
            p = tf.add_paragraph()
        else:
            p = tf.paragraphs[0]
            first = False
        p.text = heading
        p.font.size = Pt(font_size + 1)
        p.font.bold = True
        p.level = 0

        if isinstance(body, str):
            lines = body.split("\n")
        else:
            lines = body
        for line in lines:
            bp = tf.add_paragraph()
            bp.text = line
            bp.level = 1 if isinstance(body, list) else 0
            bp.font.size = Pt(font_size)


def add_demo_image(slide, module_id: str) -> None:
    png = DEMO_DIR / f"{module_id}-demo.png"
    gif = ROOT / "public" / "media" / f"{module_id}.gif"
    path = gif if gif.exists() else png
    if not path.exists():
        return
    # Right column area (matches Content Placeholder 4)
    slide.shapes.add_picture(
        str(path),
        Emu(6248400), Emu(1676400), Emu(5562600), Emu(4572000)
    )


def slide_title(prs):
    layout = get_layout(prs, *LAYOUT_TITLE_IMAGE)
    slide = prs.slides.add_slide(layout)
    for shape in slide.shapes:
        if not shape.has_text_frame:
            continue
        name = shape.name.lower()
        if "maintitle" in name or (shape.is_placeholder and shape.placeholder_format.idx == 0):
            set_ph_text(shape, "GuidewireAI\nSDLC Test Accelerators", 32)
        elif "subtitle" in name:
            set_ph_text(shape, "Seven AI modules for Guidewire InsuranceSuite — from stories to triage", 16)
        elif "text placeholder" in name and "date" not in name and "legal" not in name:
            set_ph_text(shape, "NTT DATA Guidewire Practice · July 2026", 12)
    return slide


def slide_agenda(prs):
    layout = get_layout(prs, *LAYOUT_TITLE_1COL)
    slide = prs.slides.add_slide(layout)
    set_ph_text(find_placeholder(slide, 0), "Agenda", 28)
    set_body_bullets(find_placeholder(slide, 14), [
        ("", [
            "1. Executive summary — why these accelerators matter",
            "2. The seven AI accelerators (demo, example, purpose each)",
            "3. Katalon Flow Automation — execution companion",
            "4. Productionalisation roadmap (pilot → enterprise)",
            "5. Recommended adoption path & next steps",
        ]),
    ], 14)
    return slide


def slide_executive(prs):
    layout = get_layout(prs, *LAYOUT_TITLE_SUB_1COL)
    slide = prs.slides.add_slide(layout)
    set_ph_text(find_placeholder(slide, 0), "Executive summary", 24)
    set_ph_text(find_placeholder(slide, 13), "Seven AI accelerators compress manual work across the Guidewire testing lifecycle", 14)
    set_body_bullets(find_placeholder(slide, 14), [
        ("The challenge", [
            "Test design, UI automation, manual-to-auto conversion and defect triage consume 40–60% of sprint capacity",
            "Inconsistent standards across delivery centres and geographies",
            "UI regression rots with every customisation and ski release",
        ]),
        ("Our response", [
            "7 Claude-powered modules mapped Plan → Build → Test → Release → Operate",
            "Bundled reference material (/katalon, GW standards, ski-release themes)",
            "Per-project RAG over client standards and saved artifacts",
            "Katalon companion: 12 ready-to-run flows across PC · CC · BC · Jutro",
        ]),
    ], 12)
    return slide


def slide_section(prs, title: str, subtitle: str):
    layout = get_layout(prs, *LAYOUT_TITLE_ONLY)
    slide = prs.slides.add_slide(layout)
    set_ph_text(find_placeholder(slide, 0), title, 28)
    # Some title-only layouts have extra text placeholders
    for shape in slide.shapes:
        if shape.has_text_frame and shape.name.startswith("Text Placeholder"):
            set_ph_text(shape, subtitle, 14)
            break
    return slide


def slide_accelerator(prs, acc: dict):
    layout = get_layout(prs, *LAYOUT_TITLE_SUB_2COL)
    slide = prs.slides.add_slide(layout)
    set_ph_text(find_placeholder(slide, 0), f"{acc['name']} — {acc['phase']}", 22)
    set_ph_text(find_placeholder(slide, 13), acc["tagline"], 13)

    left = find_placeholder(slide, 14)
    set_body_bullets(left, [
        ("Purpose", acc["purpose"]),
        ("Example", acc["example"]),
        ("Key capabilities", acc["capabilities"]),
        ("Productionalise", acc["prod"]),
        ("Indicative ROI", acc["roi"]),
    ], 10)

    add_demo_image(slide, acc["id"])
    return slide


def slide_katalon(prs):
    layout = get_layout(prs, *LAYOUT_TITLE_SUB_1COL)
    slide = prs.slides.add_slide(layout)
    set_ph_text(find_placeholder(slide, 0), "Companion asset — Katalon Flow Automation", 22)
    set_ph_text(find_placeholder(slide, 13), "Physical execution layer behind Flow Automator and Test Migrator (Katalon framework)", 13)
    set_body_bullets(find_placeholder(slide, 14), [
        ("What ships in /katalon", [
            "12 flows: PC01–PC04 · CC01–CC03 · BC01–BC03 · JU01–JU02",
            "Keyword libraries: PolicyCenterActions, ClaimCenterActions, BillingCenterActions, JutroActions",
            "Shared: GuidewireUI · LoginActions · TestData",
        ]),
        ("Productionalise", [
            "Open GuidewireFlowAutomation.prj in Katalon Studio 8.x+",
            "Swap URLs/credentials via execution profiles (default.glbl, qa.glbl)",
            "Run headless: katalonc in CI with Runtime Engine + secret-injected profiles",
            "Adapt locators in one keyword library per product when screens are customised",
        ]),
    ], 11)
    return slide


def slide_production(prs):
    layout = get_layout(prs, *LAYOUT_TITLE_SUB_1COL)
    slide = prs.slides.add_slide(layout)
    set_ph_text(find_placeholder(slide, 0), "Productionalisation roadmap", 22)
    set_ph_text(find_placeholder(slide, 13), "From internal demo to client-ready, governed service", 13)
    set_body_bullets(find_placeholder(slide, 14), [
        ("Phase 0 — Now (demo)", [
            "Vercel + Anthropic + Neon; bundled reference material + RAG",
            "No auth; auto-schema; suitable for showcases and pilots",
        ]),
        ("Phase 1 — Pilot hardening", [
            "SSO / edge auth, rate limits, input validation, structured logging",
            "Versioned DB migrations; branch protection + CI build",
        ]),
        ("Phase 2 — Client-ready", [
            "Multi-tenant row scoping, audit log, data classification",
            "Prompt evals in CI; Katalon in CI with KRE",
            "VOYAGE_API_KEY for production-grade RAG embeddings",
        ]),
        ("Phase 3 — Enterprise scale", [
            "SLOs, token budgets, schema-validated outputs",
            "Katalon TestOps, grid parallelism, API-driven test data seeding",
        ]),
    ], 11)
    return slide


def slide_adoption(prs):
    layout = get_layout(prs, *LAYOUT_TITLE_1COL)
    slide = prs.slides.add_slide(layout)
    set_ph_text(find_placeholder(slide, 0), "Recommended adoption path", 24)
    set_body_bullets(find_placeholder(slide, 14), [
        ("", [
            "Week 1 — Discover & demo: Defect Triage + Flow Automator + Katalon live",
            "Weeks 2–4 — Pilot: Story Forge on grooming, Code Review on real Gosu, Test Migrator on 10–20 cases",
            "Month 2+ — Embed: Jira/ADO export, Katalon in CI, Code Review as pre-PR gate",
            "Ongoing — Measure ROI per module; extend Project knowledge and /katalon libraries",
        ]),
    ], 13)
    return slide


def slide_closing(prs):
    layout = get_layout(prs, *LAYOUT_TITLE_IMAGE)
    slide = prs.slides.add_slide(layout)
    for shape in slide.shapes:
        if not shape.has_text_frame:
            continue
        name = shape.name.lower()
        if "maintitle" in name or (shape.is_placeholder and shape.placeholder_format.idx == 0):
            set_ph_text(shape, "Next steps", 36)
        elif "subtitle" in name:
            set_ph_text(shape, "Deploy · Demo · Deliver", 20)
        elif "text placeholder" in name and "date" not in name:
            set_ph_text(shape, "Deploy to Vercel · Schedule client showcase · Open /katalon in Katalon Studio\nNTT DATA Guidewire Practice · GuidewireAI · Confidential", 12)
    return slide


def ensure_demos():
    script = ROOT / "scripts" / "generate-accelerator-demos.py"
    subprocess.run([sys.executable, str(script)], check=True)
    for gif_script in ["generate-code-review-gif.py", "generate-defect-triage-gif.py"]:
        path = ROOT / "scripts" / gif_script
        if path.exists():
            subprocess.run([sys.executable, str(path)], check=False)


def build():
    if not TEMPLATE.exists():
        raise SystemExit(f"Template not found: {TEMPLATE}")

    ensure_demos()

    prs = Presentation(str(TEMPLATE))
    delete_all_slides(prs)

    slide_title(prs)
    slide_agenda(prs)
    slide_executive(prs)
    slide_section(prs, "The seven AI accelerators", "Purpose · live demo preview · example · how to productionalise")
    for acc in ACCELERATORS:
        slide_accelerator(prs, acc)
    slide_section(prs, "Productionalise the suite", "Roadmap, CI integration and governance")
    slide_katalon(prs)
    slide_production(prs)
    slide_adoption(prs)
    slide_closing(prs)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    prs.save(str(OUT))
    print(f"Wrote {OUT} ({len(prs.slides)} slides)")


if __name__ == "__main__":
    build()
